### ISSUE TITLE
I am nub. Add how to use to README

### ISSUE THREAD

**Issue by kikisaints** [bstrukus/rt#12]
Can you expand the README section to include steps on how to setup and pass in the scenes to render when running from the command prompts?

I get this error:
![image](https://user-images.githubusercontent.com/6964369/146279742-c1d9ecd8-174e-4a46-932f-9f19d0e7dddf.png)

Because I am not passing in any args to run the program, but I'm not sure which ones I should be passing or what the cmd line is for that. Documentation would be greatly appreciated.

**Comment by bstrukus** [comment]
Thanks for logging this issue, you're right! I've updated the `README.md` to explain how to use this project. Please open a new issue if you continue to run into problems.
